typography_spectrum: 0.7456691530533135
color:
  brandStrength: 0.49163007782772183
  lightness: 0.16648017708212137
  saturation: 0.6504551297985017
  rhythmicContrast: 0.6892318960744888
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.45277713844552636
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5bbf50de-c714-4eca-a9df-1edcd073d15b.jpg
name: TTE 2
navigation:
  - id: 2c8aba27-c54c-4d4b-b58d-053097e73f8e
    name: History
    type: content
title: TEA TIME EXPRESS
description: 'Exquisite, Hand Made Triple Layered Cakes'
