typography_spectrum: 0.7456691530533135
color:
  brandStrength: 0.49163007782772183
  lightness: 0.16648017708212137
  saturation: 0.6504551297985017
  rhythmicContrast: 0.6892318960744888
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.45277713844552636
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5bbf50de-c714-4eca-a9df-1edcd073d15b.jpg
name: TEA TIME EXPRESS
title: TEA TIME EXPRESS
description: 'Exquisite, Hand Made triple layered cakes'
